from __future__ import annotations

from src.analysis.shared.contracts import (
    ARTICLE_TYPES,
    BIAS_LABELS,
    EVIDENCE_SPAN_TYPES,
    FRAMING_DEVICE_VALUES,
    OPINIONATEDNESS_VALUES,
    RHETORICAL_CERTAINTY_VALUES,
    SENSATIONALISM_VALUES,
    TONE_EMOTIONAL_VALUES,
    TONE_TARGET_VALUES,
)

ARTICLE_TYPE_ALIASES = {
    "breaking_news": "news_report",
    "breaking_news_crime_report": "news_report",
    "crime_report": "news_report",
    "crime_news": "news_report",
    "noticia_accidente": "news_report",
    "straight_news": "news_report",
    "straight_reporting": "news_report",
    "news": "news_report",
    "report": "news_report",
    "match_report": "news_report",
    "election_results_report": "news_report",
    "local_news_event_coverage": "news_report",
    "analysis_piece": "analysis",
    "op_ed": "opinion",
    "op-ed": "opinion",
    "column": "opinion",
    "qa": "interview",
    "q&a": "interview",
    "longform_feature": "feature",
    "long_form_feature": "feature",
    "backgrounder": "explainer",
}
BIAS_LABEL_ALIASES = {
    "far-left": "far_left",
    "center-left": "center_left",
    "centre-left": "center_left",
    "centre": "center",
    "centered": "center",
    "center-right": "center_right",
    "centre-right": "center_right",
    "far-right": "far_right",
    "neutral": "unclear",
    "none": "unclear",
    "no_bias": "unclear",
    "non_ideological": "unclear",
    "sin_sesgo_claro": "unclear",
    "pro_real_madrid": "unclear",
    "protester_sympathetic": "unclear",
}
TONE_EMOTIONAL_ALIASES = {
    "neutral": "calm",
    "objective": "calm",
    "restrained": "calm",
    "descriptive": "calm",
    "factual": "calm",
    "measured": "calm",
    "informative_and_sober": "calm",
    "informativo_y_sobrio": "calm",
    "low": "calm",
    "baja": "calm",
    "bajo": "calm",
    "false": "calm",
    "moderate": "loaded",
    "medium": "loaded",
    "high": "loaded",
    "very_high": "inflammatory",
    "emotional": "loaded",
    "charged": "loaded",
    "alarmist": "inflammatory",
    "provocative": "inflammatory",
    "none": "calm",
}
TONE_TARGET_ALIASES = {
    "balanced": "mixed",
    "ambivalent": "mixed",
    "negative": "critical",
    "adversarial": "hostile",
    "positive": "supportive",
    "objective": "neutral",
    "none": "neutral",
    "partial": "mixed",
    "false": "neutral",
}
OPINIONATEDNESS_ALIASES = {
    "objective_reporting": "straight_reporting",
    "factual_reporting": "straight_reporting",
    "news_reporting": "straight_reporting",
    "analysis": "interpretive",
    "commentary": "opinionated",
    "advocacy": "activist",
    "neutral": "straight_reporting",
    "absent": "opinionated",
    "high": "opinionated",
    "moderate": "interpretive",
    "low": "straight_reporting",
    "false": "straight_reporting",
}
SENSATIONALISM_ALIASES = {
    "none": "low",
    "minimal": "low",
    "low": "low",
    "bajo": "low",
    "baja": "low",
    "moderate": "medium",
    "media": "medium",
    "medio": "medium",
    "elevated": "medium",
    "very_high": "high",
    "alta": "high",
    "alto": "high",
    "false": "low",
    "true": "medium",
}
RHETORICAL_CERTAINTY_ALIASES = {
    "measured": "cautious",
    "qualified": "cautious",
    "neutral": "assertive",
    "factual": "assertive",
    "direct": "assertive",
    "categorical": "absolute",
    "dogmatic": "absolute",
    "high": "assertive",
    "moderate": "assertive",
    "low": "cautious",
}
FRAMING_DEVICE_ALIASES = {
    "security": "public_order_security",
    "law_and_order": "public_order_security",
    "public_safety": "public_order_security",
    "crime_public_safety": "public_order_security",
    "order_and_security": "public_order_security",
    "geopolitics": "strategic_geopolitics",
    "strategic_security": "strategic_geopolitics",
    "stability": "institutional_stability",
    "institutional_continuity": "institutional_stability",
    "anti_corruption": "corruption_scandal",
    "corruption": "corruption_scandal",
    "victim_frame": "victimization",
    "human_rights": "humanitarian",
    "culture_war": "identity_culture",
    "economic_impact": "economic_consequence",
    "competence": "governance_competence",
    "conflict_frame": "conflict",
    "moral_frame": "moral_judgment",
    "modernization": "progress_modernization",
    "martial_warfare": "conflict",
    "crisis_framing": "conflict",
    "binary_framing": "conflict",
    "headline_ambiguity": "conflict",
    "religious_sacramental": "moral_judgment",
    "heroic_narrative": "victimization",
    "epic_heroic": "victimization",
    "heroes_victims": "victimization",
    "regional_pride": "identity_culture",
    "movement_legitimacy_language": "identity_culture",
    "impact_amplification": "economic_consequence",
    "quantitative_acceleration": "economic_consequence",
    "scope_expansion": "institutional_stability",
    "growth_framing": "conflict",
    "collective_action": "conflict",
    "grassroots_legitimacy": "identity_culture",
    "rural_urban_tension": "identity_culture",
    "preventive_advocacy": "moral_judgment",
    "accusatory_headline": "conflict",
    "no_counterbalance": "conflict",
    "procedural_focus": "institutional_stability",
    "direct_quote": "institutional_stability",
    "single_source": "institutional_stability",
    "direct_quotation_of_critical_questions": "conflict",
    "opposition_questions_as_headline_focus": "conflict",
    "multiple_party_coverage_for_balance": "institutional_stability",
    "temporal_framing_emphasizing_finality": "institutional_stability",
}
CONFIDENCE_LABEL_ALIASES = {
    "low": 0.25,
    "bajo": 0.25,
    "baja": 0.25,
    "moderate": 0.5,
    "medium": 0.5,
    "medio": 0.5,
    "media": 0.5,
    "high": 0.75,
    "alto": 0.75,
    "alta": 0.75,
}
RAW_EVIDENCE_WORKING_CAP = 6
RAW_FRAMING_WORKING_CAP = 12

BIAS_SCORE_BY_LABEL = {
    "far_left": -0.9,
    "left": -0.65,
    "center_left": -0.35,
    "center": 0.0,
    "center_right": 0.35,
    "right": 0.65,
    "far_right": 0.9,
    "unclear": 0.0,
}
OUT_OF_DOMAIN_KEYWORDS = {
    "sports_recap": ("liga", "gol", "partido", "entrenador", "victoria", "derrota", "champions"),
    "accident_crime_bulletin": (
        "accidente",
        "herido",
        "muerto",
        "emergencias",
        "suceso",
        "arma blanca",
        "tráfico",
    ),
    "consumer_price_roundup": (
        "precio",
        "euros",
        "ofertas",
        "hoteles",
        "viajar",
        "gasolina",
        "supermercado",
    ),
    "weather_or_service_info": (
        "temperaturas",
        "lluvia",
        "tráfico",
        "cortes",
        "aviso amarillo",
        "servicio",
    ),
}

__all__ = [
    "ARTICLE_TYPES",
    "ARTICLE_TYPE_ALIASES",
    "BIAS_LABELS",
    "BIAS_LABEL_ALIASES",
    "BIAS_SCORE_BY_LABEL",
    "CONFIDENCE_LABEL_ALIASES",
    "EVIDENCE_SPAN_TYPES",
    "FRAMING_DEVICE_ALIASES",
    "FRAMING_DEVICE_VALUES",
    "OPINIONATEDNESS_ALIASES",
    "OPINIONATEDNESS_VALUES",
    "OUT_OF_DOMAIN_KEYWORDS",
    "RAW_EVIDENCE_WORKING_CAP",
    "RAW_FRAMING_WORKING_CAP",
    "RHETORICAL_CERTAINTY_ALIASES",
    "RHETORICAL_CERTAINTY_VALUES",
    "SENSATIONALISM_ALIASES",
    "SENSATIONALISM_VALUES",
    "TONE_EMOTIONAL_ALIASES",
    "TONE_EMOTIONAL_VALUES",
    "TONE_TARGET_ALIASES",
    "TONE_TARGET_VALUES",
]
